# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright © 2025 Intel Corporation

inc_debuginfo = include_directories('../../include/llvm/DebugInfo')

subdir('DWARF')
subdir('GSYM')
subdir('MSF')
subdir('CodeView')
subdir('PDB')
subdir('BTF')
subdir('Symbolize')
# TODO: subdir('LogicalView')
