# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright © 2025 Intel Corporation

lib_scalar_opts = library(
  'LLVMScalarOpts',
  [
    'ADCE.cpp',
    'AlignmentFromAssumptions.cpp',
    'AnnotationRemarks.cpp',
    'BDCE.cpp',
    'CallSiteSplitting.cpp',
    'ConstantHoisting.cpp',
    'ConstraintElimination.cpp',
    'CorrelatedValuePropagation.cpp',
    'DCE.cpp',
    'DeadStoreElimination.cpp',
    'DFAJumpThreading.cpp',
    'DivRemPairs.cpp',
    'EarlyCSE.cpp',
    'FlattenCFGPass.cpp',
    'Float2Int.cpp',
    'GuardWidening.cpp',
    'GVN.cpp',
    'GVNHoist.cpp',
    'GVNSink.cpp',
    'IVUsersPrinter.cpp',
    'InductiveRangeCheckElimination.cpp',
    'IndVarSimplify.cpp',
    'InferAddressSpaces.cpp',
    'InferAlignment.cpp',
    'InstSimplifyPass.cpp',
    'JumpThreading.cpp',
    'JumpTableToSwitch.cpp',
    'LICM.cpp',
    'LoopAccessAnalysisPrinter.cpp',
    'LoopBoundSplit.cpp',
    'LoopSink.cpp',
    'LoopDeletion.cpp',
    'LoopDataPrefetch.cpp',
    'LoopDistribute.cpp',
    'LoopFuse.cpp',
    'LoopIdiomRecognize.cpp',
    'LoopInstSimplify.cpp',
    'LoopInterchange.cpp',
    'LoopFlatten.cpp',
    'LoopLoadElimination.cpp',
    'LoopPassManager.cpp',
    'LoopPredication.cpp',
    'LoopRotation.cpp',
    'LoopSimplifyCFG.cpp',
    'LoopStrengthReduce.cpp',
    'LoopTermFold.cpp',
    'LoopUnrollPass.cpp',
    'LoopUnrollAndJamPass.cpp',
    'LoopVersioningLICM.cpp',
    'LowerAtomicPass.cpp',
    'LowerConstantIntrinsics.cpp',
    'LowerExpectIntrinsic.cpp',
    'LowerGuardIntrinsic.cpp',
    'LowerMatrixIntrinsics.cpp',
    'LowerWidenableCondition.cpp',
    'MakeGuardsExplicit.cpp',
    'MemCpyOptimizer.cpp',
    'MergeICmps.cpp',
    'MergedLoadStoreMotion.cpp',
    'NaryReassociate.cpp',
    'NewGVN.cpp',
    'PartiallyInlineLibCalls.cpp',
    'PlaceSafepoints.cpp',
    'Reassociate.cpp',
    'Reg2Mem.cpp',
    'RewriteStatepointsForGC.cpp',
    'SCCP.cpp',
    'SROA.cpp',
    'Scalar.cpp',
    'Scalarizer.cpp',
    'ScalarizeMaskedMemIntrin.cpp',
    'SeparateConstOffsetFromGEP.cpp',
    'SimpleLoopUnswitch.cpp',
    'SimplifyCFGPass.cpp',
    'Sink.cpp',
    'SpeculativeExecution.cpp',
    'StraightLineStrengthReduce.cpp',
    'StructurizeCFG.cpp',
    'TailRecursionElimination.cpp',
    'WarnMissedTransforms.cpp',
    gen_intrinsics,
  ],
  include_directories : [
    '../../../include/llvm/Transforms',
    '../../../include/llvm/Transforms/Scalar',
  ],
  dependencies : [
    component_aggressive_inst_combine, component_analysis, component_core,
    component_support, component_support, component_transform_utils,
  ],
  install : true,
)

component_scalar = declare_dependency(
  link_with : lib_scalar_opts,
)

