# SPDX-License-Identifier: <<spdxid>>
# Copyright © 2025 Intel Corporation

_support_cpp_args = []

if cpp.has_argument('-Werror=global-constructors')
  if cpp.compiles('''
      #include <mutex>
      static std::mutex TestGlobalCtorDtor;
      static std::recursive_mutex TestGlobalCtorDtor2;
      int main() { (void)TestGlobalCtorDtor; (void)TestGlobalCtorDtor2; return 0;}''',
      args : '-Werror=global-constructors',
      name : 'LLVM_HAS_NOGLOBAL_CTOR_MUTEX')
    extra_cpp_args += ['-Werror=global-constructors']
  endif
endif

# TODO: win32
# TODO: atomic
# TODO: pthread
# TODO: sunos
# TODO: fuschsia
# TODO: haiku
# TODO: IntelLMVM
# TODO: swift
# TODO: Z3
_support_allocator_files = []
# TODO: INTEGRATED_CRT
# TODO: AIX

subdir('BLAKE3')

lib_llvm_support = static_library(
  'LLVMSupport',
  'ABIBreak.cpp',
  'AMDGPUMetadata.cpp',
  'APFixedPoint.cpp',
  'APFloat.cpp',
  'APInt.cpp',
  'APSInt.cpp',
  'ARMBuildAttributes.cpp',
  'AArch64BuildAttributes.cpp',
  'ARMAttributeParser.cpp',
  'ARMWinEH.cpp',
  'Allocator.cpp',
  'AutoConvert.cpp',
  'Base64.cpp',
  'BalancedPartitioning.cpp',
  'BinaryStreamError.cpp',
  'BinaryStreamReader.cpp',
  'BinaryStreamRef.cpp',
  'BinaryStreamWriter.cpp',
  'BlockFrequency.cpp',
  'BranchProbability.cpp',
  'BuryPointer.cpp',
  'CachePruning.cpp',
  'Caching.cpp',
  'circular_raw_ostream.cpp',
  'Chrono.cpp',
  'COM.cpp',
  'CodeGenCoverage.cpp',
  'CommandLine.cpp',
  'Compression.cpp',
  'CRC.cpp',
  'ConvertUTF.cpp',
  'ConvertEBCDIC.cpp',
  'ConvertUTFWrapper.cpp',
  'CrashRecoveryContext.cpp',
  'CSKYAttributes.cpp',
  'CSKYAttributeParser.cpp',
  'DataExtractor.cpp',
  'Debug.cpp',
  'DebugCounter.cpp',
  'DeltaAlgorithm.cpp',
  'DeltaTree.cpp',
  'DivisionByConstantInfo.cpp',
  'DAGDeltaAlgorithm.cpp',
  'DJB.cpp',
  'DynamicAPInt.cpp',
  'ELFAttributeParser.cpp',
  'ELFAttributes.cpp',
  'Error.cpp',
  'ErrorHandling.cpp',
  'ExponentialBackoff.cpp',
  'ExtensibleRTTI.cpp',
  'FileCollector.cpp',
  'FileUtilities.cpp',
  'FileOutputBuffer.cpp',
  'FloatingPointMode.cpp',
  'FoldingSet.cpp',
  'FormattedStream.cpp',
  'FormatVariadic.cpp',
  'GlobPattern.cpp',
  'GraphWriter.cpp',
  'HexagonAttributeParser.cpp',
  'HexagonAttributes.cpp',
  'InitLLVM.cpp',
  'InstructionCost.cpp',
  'IntEqClasses.cpp',
  'IntervalMap.cpp',
  'JSON.cpp',
  'KnownBits.cpp',
  'LEB128.cpp',
  'LineIterator.cpp',
  'Locale.cpp',
  'LockFileManager.cpp',
  'ManagedStatic.cpp',
  'MathExtras.cpp',
  'MemAlloc.cpp',
  'MemoryBuffer.cpp',
  'MemoryBufferRef.cpp',
  'ModRef.cpp',
  'MD5.cpp',
  'MSP430Attributes.cpp',
  'MSP430AttributeParser.cpp',
  'NativeFormatting.cpp',
  'OptimizedStructLayout.cpp',
  'Optional.cpp',
  'OptionStrCmp.cpp',
  'PGOOptions.cpp',
  'Parallel.cpp',
  'PluginLoader.cpp',
  'PrettyStackTrace.cpp',
  'RandomNumberGenerator.cpp',
  'Regex.cpp',
  'RewriteBuffer.cpp',
  'RewriteRope.cpp',
  'RISCVAttributes.cpp',
  'RISCVAttributeParser.cpp',
  'RISCVISAUtils.cpp',
  'ScaledNumber.cpp',
  'ScopedPrinter.cpp',
  'SHA1.cpp',
  'SHA256.cpp',
  'Signposts.cpp',
  'SipHash.cpp',
  'SlowDynamicAPInt.cpp',
  'SmallPtrSet.cpp',
  'SmallVector.cpp',
  'SourceMgr.cpp',
  'SpecialCaseList.cpp',
  'Statistic.cpp',
  'StringExtras.cpp',
  'StringMap.cpp',
  'StringSaver.cpp',
  'StringRef.cpp',
  'SuffixTreeNode.cpp',
  'SuffixTree.cpp',
  'SystemUtils.cpp',
  'TarWriter.cpp',
  'ThreadPool.cpp',
  'TimeProfiler.cpp',
  'Timer.cpp',
  'ToolOutputFile.cpp',
  'TrieRawHashMap.cpp',
  'Twine.cpp',
  'TypeSize.cpp',
  'Unicode.cpp',
  'UnicodeCaseFold.cpp',
  'UnicodeNameToCodepoint.cpp',
  'UnicodeNameToCodepointGenerated.cpp',
  'VersionTuple.cpp',
  'VirtualFileSystem.cpp',
  'WithColor.cpp',
  'YAMLParser.cpp',
  'YAMLTraits.cpp',
  'raw_os_ostream.cpp',
  'raw_ostream.cpp',
  'raw_socket_stream.cpp',
  'regcomp.c',
  'regerror.c',
  'regexec.c',
  'regfree.c',
  'regstrlcpy.c',
  'xxhash.cpp',
  'Z3Solver.cpp',
  'Atomic.cpp',
  'DynamicLibrary.cpp',
  'Errno.cpp',
  'Memory.cpp',
  'Path.cpp',
  'Process.cpp',
  'Program.cpp',
  'RWMutex.cpp',
  'Signals.cpp',
  'Threading.cpp',
  'Valgrind.cpp',
  'Watchdog.cpp',
  _support_allocator_files,
  cpp_args : _support_cpp_args,
  dependencies : [deps_system, dep_zlib, dep_zstd],
  install : true,
)

component_support = declare_dependency(
  link_with : lib_llvm_support,
  dependencies : [dep_zstd, dep_zlib],
)
