# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright © 2025 Intel Corporation

lib_mc = library(
  'LLVMMC',
  [
    'ConstantPools.cpp',
    'DXContainerPSVInfo.cpp',
    'ELFObjectWriter.cpp',
    'GOFFObjectWriter.cpp',
    'MCAsmBackend.cpp',
    'MCAsmInfo.cpp',
    'MCAsmInfoCOFF.cpp',
    'MCAsmInfoDarwin.cpp',
    'MCAsmInfoELF.cpp',
    'MCAsmInfoGOFF.cpp',
    'MCAsmInfoWasm.cpp',
    'MCAsmInfoXCOFF.cpp',
    'MCAsmMacro.cpp',
    'MCAsmStreamer.cpp',
    'MCAssembler.cpp',
    'MCCodeEmitter.cpp',
    'MCCodeView.cpp',
    'MCContext.cpp',
    'MCDwarf.cpp',
    'MCDXContainerStreamer.cpp',
    'MCDXContainerWriter.cpp',
    'MCELFObjectTargetWriter.cpp',
    'MCELFStreamer.cpp',
    'MCExpr.cpp',
    'MCFragment.cpp',
    'MCGOFFStreamer.cpp',
    'MCInst.cpp',
    'MCInstPrinter.cpp',
    'MCInstrAnalysis.cpp',
    'MCInstrDesc.cpp',
    'MCInstrInfo.cpp',
    'MCLabel.cpp',
    'MCLinkerOptimizationHint.cpp',
    'MCMachOStreamer.cpp',
    'MCMachObjectTargetWriter.cpp',
    'MCNullStreamer.cpp',
    'MCObjectFileInfo.cpp',
    'MCObjectStreamer.cpp',
    'MCObjectWriter.cpp',
    'MCPseudoProbe.cpp',
    'MCRegisterInfo.cpp',
    'MCSchedule.cpp',
    'MCSection.cpp',
    'MCSectionCOFF.cpp',
    'MCSectionDXContainer.cpp',
    'MCSectionELF.cpp',
    'MCSectionMachO.cpp',
    'MCSectionWasm.cpp',
    'MCSectionXCOFF.cpp',
    'MCStreamer.cpp',
    'MCSPIRVStreamer.cpp',
    'MCSubtargetInfo.cpp',
    'MCSymbol.cpp',
    'MCSymbolELF.cpp',
    'MCSymbolXCOFF.cpp',
    'MCTargetOptions.cpp',
    'MCTargetOptionsCommandFlags.cpp',
    'MCValue.cpp',
    'MCWasmObjectTargetWriter.cpp',
    'MCWasmStreamer.cpp',
    'MCWin64EH.cpp',
    'MCWinCOFFStreamer.cpp',
    'MCWinEH.cpp',
    'MCXCOFFObjectTargetWriter.cpp',
    'MCXCOFFStreamer.cpp',
    'MachObjectWriter.cpp',
    'SPIRVObjectWriter.cpp',
    'StringTableBuilder.cpp',
    'TargetRegistry.cpp',
    'WasmObjectWriter.cpp',
    'WinCOFFObjectWriter.cpp',
    'XCOFFObjectWriter.cpp',
    gen_intrinsics,
  ],
  include_directories : '../../include/llvm/MC',
  dependencies : [
    component_support, component_target_parser, component_binary_format,
  ],
  install : true,
)

component_mc = declare_dependency(
  link_with : lib_mc,
)

subdir('MCParser')
subdir('MCDisassembler')
