# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright © 2025 Intel Corporation

_lib = library(
  'LLVMOrcJIT',
  [
    'AbsoluteSymbols.cpp',
    'COFFVCRuntimeSupport.cpp',
    'COFFPlatform.cpp',
    'CompileOnDemandLayer.cpp',
    'CompileUtils.cpp',
    'Core.cpp',
    'DebugObjectManagerPlugin.cpp',
    'DebugUtils.cpp',
    'EHFrameRegistrationPlugin.cpp',
    'EPCDynamicLibrarySearchGenerator.cpp',
    'EPCDebugObjectRegistrar.cpp',
    'EPCEHFrameRegistrar.cpp',
    'EPCGenericDylibManager.cpp',
    'EPCGenericJITLinkMemoryManager.cpp',
    'EPCGenericRTDyldMemoryManager.cpp',
    'EPCIndirectionUtils.cpp',
    'ExecutionUtils.cpp',
    'ObjectFileInterface.cpp',
    'IndirectionUtils.cpp',
    'IRCompileLayer.cpp',
    'IRTransformLayer.cpp',
    'IRPartitionLayer.cpp',
    'JITTargetMachineBuilder.cpp',
    'JITLinkReentryTrampolines.cpp',
    'LazyObjectLinkingLayer.cpp',
    'LazyReexports.cpp',
    'Layer.cpp',
    'LinkGraphLayer.cpp',
    'LinkGraphLinkingLayer.cpp',
    'LoadLinkableFile.cpp',
    'LookupAndRecordAddrs.cpp',
    'LLJIT.cpp',
    'MachO.cpp',
    'MachOPlatform.cpp',
    'MapperJITLinkMemoryManager.cpp',
    'MemoryMapper.cpp',
    'ELFNixPlatform.cpp',
    'Mangling.cpp',
    'ObjectLinkingLayer.cpp',
    'ObjectTransformLayer.cpp',
    'OrcABISupport.cpp',
    'OrcV2CBindings.cpp',
    'RTDyldObjectLinkingLayer.cpp',
    'SectCreate.cpp',
    'SimpleRemoteEPC.cpp',
    'Speculation.cpp',
    'SpeculateAnalyses.cpp',
    'ExecutorProcessControl.cpp',
    'TaskDispatch.cpp',
    'ThreadSafeModule.cpp',
    'UnwindInfoRegistrationPlugin.cpp',
    'RedirectionManager.cpp',
    'JITLinkRedirectableSymbolManager.cpp',
    'ReOptimizeLayer.cpp',
    gen_intrinsics,
  ],
  include_directories : inc_orc,
  dependencies : [
    dep_threads, dep_rt, # TODO: atomic
    component_binary_format, component_core, component_execution_engine,
    component_jit_link, component_object, component_orc_shared,
    component_orc_target_process, component_windows_driver, component_mc,
    component_passes, component_runtime_dyld, component_support,
    component_target, component_target_parser, component_transform_utils,
  ],
  install : true,
)

component_orc_jit = declare_dependency(
  link_with : _lib,
)

subdir('Debugging')
