# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# Copyright © 2025 Intel Corporation

# TODO: add_pdb_impl_folder?
# TODO: DIA_SDK

_pdb_impl_sources = [
  'Native/DbiModuleDescriptor.cpp',
  'Native/DbiModuleDescriptorBuilder.cpp',
  'Native/DbiModuleList.cpp',
  'Native/DbiStream.cpp',
  'Native/DbiStreamBuilder.cpp',
  'Native/EnumTables.cpp',
  'Native/FormatUtil.cpp',
  'Native/GlobalsStream.cpp',
  'Native/Hash.cpp',
  'Native/HashTable.cpp',
  'Native/InfoStream.cpp',
  'Native/InfoStreamBuilder.cpp',
  'Native/InjectedSourceStream.cpp',
  'Native/InputFile.cpp',
  'Native/LinePrinter.cpp',
  'Native/ModuleDebugStream.cpp',
  'Native/NativeCompilandSymbol.cpp',
  'Native/NativeEnumGlobals.cpp',
  'Native/NativeEnumInjectedSources.cpp',
  'Native/NativeEnumLineNumbers.cpp',
  'Native/NativeEnumModules.cpp',
  'Native/NativeEnumTypes.cpp',
  'Native/NativeEnumSymbols.cpp',
  'Native/NativeExeSymbol.cpp',
  'Native/NativeFunctionSymbol.cpp',
  'Native/NativeInlineSiteSymbol.cpp',
  'Native/NativeLineNumber.cpp',
  'Native/NativePublicSymbol.cpp',
  'Native/NativeRawSymbol.cpp',
  'Native/NativeSourceFile.cpp',
  'Native/NativeSymbolEnumerator.cpp',
  'Native/NativeTypeArray.cpp',
  'Native/NativeTypeBuiltin.cpp',
  'Native/NativeTypeEnum.cpp',
  'Native/NativeTypeFunctionSig.cpp',
  'Native/NativeTypePointer.cpp',
  'Native/NativeTypeTypedef.cpp',
  'Native/NativeTypeUDT.cpp',
  'Native/NativeTypeVTShape.cpp',
  'Native/NamedStreamMap.cpp',
  'Native/NativeSession.cpp',
  'Native/PDBFile.cpp',
  'Native/PDBFileBuilder.cpp',
  'Native/PDBStringTable.cpp',
  'Native/PDBStringTableBuilder.cpp',
  'Native/PublicsStream.cpp',
  'Native/GSIStreamBuilder.cpp',
  'Native/RawError.cpp',
  'Native/SymbolCache.cpp',
  'Native/SymbolStream.cpp',
  'Native/TpiHashing.cpp',
  'Native/TpiStream.cpp',
  'Native/TpiStreamBuilder.cpp',
]

lib_debuginfo_pdb = library(
  'LLVMDebugInfoPDB',
  [
    'GenericError.cpp',
    'IPDBSourceFile.cpp',
    'PDB.cpp',
    'PDBContext.cpp',
    'PDBExtras.cpp',
    'PDBInterfaceAnchors.cpp',
    'PDBSymbol.cpp',
    'PDBSymbolAnnotation.cpp',
    'PDBSymbolBlock.cpp',
    'PDBSymbolCompiland.cpp',
    'PDBSymbolCompilandDetails.cpp',
    'PDBSymbolCompilandEnv.cpp',
    'PDBSymbolCustom.cpp',
    'PDBSymbolData.cpp',
    'PDBSymbolExe.cpp',
    'PDBSymbolFunc.cpp',
    'PDBSymbolFuncDebugEnd.cpp',
    'PDBSymbolFuncDebugStart.cpp',
    'PDBSymbolLabel.cpp',
    'PDBSymbolPublicSymbol.cpp',
    'PDBSymbolThunk.cpp',
    'PDBSymbolTypeArray.cpp',
    'PDBSymbolTypeBaseClass.cpp',
    'PDBSymbolTypeBuiltin.cpp',
    'PDBSymbolTypeCustom.cpp',
    'PDBSymbolTypeDimension.cpp',
    'PDBSymbolTypeEnum.cpp',
    'PDBSymbolTypeFriend.cpp',
    'PDBSymbolTypeFunctionArg.cpp',
    'PDBSymbolTypeFunctionSig.cpp',
    'PDBSymbolTypeManaged.cpp',
    'PDBSymbolTypePointer.cpp',
    'PDBSymbolTypeTypedef.cpp',
    'PDBSymbolTypeUDT.cpp',
    'PDBSymbolTypeVTable.cpp',
    'PDBSymbolTypeVTableShape.cpp',
    'PDBSymbolUnknown.cpp',
    'PDBSymbolUsingNamespace.cpp',
    'PDBSymDumper.cpp',
    'UDTLayout.cpp',
    _pdb_impl_sources,
  ],
  include_directories : [
    '../../../include/llvm/DebugInfo/PDB/Native',
    '../../../include/llvm/DebugInfo/PDB',
  ],
  dependencies : [
    component_binary_format, component_object, component_support,
    component_debuginfo_code_view, component_debuginfo_msf,
  ],
  install : true,
)

component_debuginfo_pdb = declare_dependency(
  link_with : lib_debuginfo_pdb,
)
